Ignore the build/`-directory when testing
Locally for me the `npm test` failed with messages as follows.

    FAIL  build/examples/Util/FeatureUtil.spec.js
    ● Test suite failed to run

    Cannot find module 'expect.js' from 'FeatureUtil.spec.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (build/examples/Util/FeatureUtil.spec.js:2:15)

I know that #231 will ensure that no spec files will be copied over, and this
is not a replacement for that PR.